{
 "title": "Slurm overview",
 "description": "Slurm exporter statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(slurm_partition_total_cpus, partition)"
    }
   },
   {
    "name": "jobid",
    "query": {
     "query": "label_values(slurm_proc_cpu_usage, jobid)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(slurm_cpus_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Problem Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_count_per_state{state=\"draining\", instance=\"$instance\"}",
     "legendFormat": "draining"
    },
    {
     "expr": "slurm_node_count_per_state{state=\"mixed\", instance=\"$instance\"}",
     "legendFormat": "mixed"
    },
    {
     "expr": "slurm_node_count_per_state{state=\"idle\", instance=\"$instance\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Slurmctld RPC Load",
   "type": "gauge",
   "description": "Total number of new RPC calls made to the daemon every $__interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(slurm_rpc_user_count{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Slurm Node States",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "slurm_node_count_per_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Slurm CPU States",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "slurm_cpus_per_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "slurm_cpus_total{instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Cluster Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(slurm_partition_free_mem{instance=\"$instance\"} / slurm_partition_real_mem{instance=\"$instance\"}) ",
     "legendFormat": "free mem %"
    },
    {
     "expr": "avg(slurm_partition_alloc_mem{instance=\"$instance\"} / slurm_partition_real_mem{instance=\"$instance\"})",
     "legendFormat": "alloc mem %"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "description": "Cpu utilization is reported by slurm per node based on linux's definition on load. typically an avg over a short period of time",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(slurm_partition_cpu_load{instance=\"$instance\"} / slurm_partition_total_cpus{instance=\"$instance\"})",
     "legendFormat": "avg cpu utilization"
    }
   ]
  },
  { "title": "Account Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Account CPU alloc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "slurm_account_cpu_alloc{instance=\"$instance\"}",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(slurm_account_cpu_alloc{instance=\"$instance\"})",
     "legendFormat": "Total Account Alloc"
    }
   ]
  },
  {
   "title": "Account Mem Alloc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "slurm_account_mem_alloc", "legendFormat": "{{account}}" },
    { "expr": "sum(slurm_account_mem_alloc)", "legendFormat": "Total Account Alloc" }
   ]
  },
  { "title": "Partition Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Pending Jobs per Partition",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{state=\"PENDING\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Alloc Cpus %",
   "type": "timeseries",
   "description": "Allocated Cpus per partition",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "slurm_partition_alloc_cpus / slurm_partition_total_cpus",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Mem Alloc %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "slurm_partition_alloc_mem / slurm_partition_real_mem",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "$partition job state totals",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{partition=\"$partition\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "User Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "User Totals",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 82 },
   "targets": [
    { "expr": "slurm_user_cpu_alloc", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Job Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tracked Usage %",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "slurm_proc_cpu_usage / on(jobid) group_right() slurm_job_cpu_alloc",
       "legendFormat": "{{jobid}} cpu usage %"
      },
      {
       "expr": "slurm_proc_mem_usage / on(jobid) group_right() (slurm_job_mem_alloc * 1000)",
       "legendFormat": "{{jobid}} mem usage %"
      }
     ]
    },
    {
     "title": "Read/Write bytes",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 131 },
     "targets": [
      { "expr": "slurm_proc_read_bytes", "legendFormat": "{{jobid}} read_bytes" },
      { "expr": "slurm_proc_write_bytes", "legendFormat": "{{jobid}} write_bytes" }
     ]
    },
    {
     "title": "Usage vs Alloc (Mem) for jobid: $jobid",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 150 },
     "targets": [
      {
       "expr": "slurm_proc_mem_usage{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} usage"
      },
      {
       "expr": "slurm_job_mem_alloc{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} alloc"
      }
     ]
    },
    {
     "title": "Usage vs Alloc (Cpu) for jobid: $jobid",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 150 },
     "targets": [
      {
       "expr": "slurm_proc_cpu_usage{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} usage"
      },
      {
       "expr": "slurm_job_cpu_alloc{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} alloc"
      }
     ]
    }
   ]
  },
  { "title": "Slurmctld Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "RPC Count Per Message Type per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_count[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RPC Count Per Message Type per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_count[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time per RPC per MSG",
   "type": "timeseries",
   "description": "Only show latencies above 100 microseconds (1 ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_avg_time{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time per RPC per User",
   "type": "timeseries",
   "description": "Only show latencies above 100 microseconds (1 ms)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(rate(slurm_rpc_user_total_time{instance=\"$instance\"}[$__rate_interval]) / on(user) rate(slurm_rpc_user_count{instance=\"$instance\"}[$__rate_interval])) > 100",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Msg Type Summary",
   "type": "piechart",
   "description": "Percentage load per Msg Type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top 25 Users",
   "type": "piechart",
   "description": "Top 25 Users by RPC Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(25, rate(slurm_rpc_user_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Exporter Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Exporter  Mem Usage",
   "type": "timeseries",
   "description": "Number of bytes allocated and in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"slurm-prod-scraper\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "rate(slurm_job_scrape_error[$__rate_interval])",
     "legendFormat": "job scrape error"
    },
    {
     "expr": "rate(slurm_node_scrape_error[$__rate_interval])",
     "legendFormat": "node scrape error"
    },
    {
     "expr": "rate(slurm_diag_scrape_error{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "diag scrape error"
    }
   ]
  },
  {
   "title": "Exporter cli scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expr": "slurm_node_scrape_duration", "legendFormat": "sinfo cli duration" },
    { "expr": "slurm_job_scrape_duration", "legendFormat": "squeue cli duration" },
    {
     "expr": "slurm_diag_scrape_duration{instance=\"$instance\"}",
     "legendFormat": "sdiag scrape duration"
    }
   ]
  }
 ]
}