---
- name: restart node-exporter
  service:
    name: "{{ node_exporter_svc_name }}"
    state: restarted

- name: restart grafana
  service:
    name: "{{ grafana_svc_name }}"
    state: restarted
  failed_when: false
