# vars for gantsign.golang
golang_version: "1.21.1"
golang_install_dir: "/opt/go/{{ golang_version }}"
golang_gopath: "/opt/go/packages"

slurm_exporter_repo: https://github.com/rivosinc/prometheus-slurm-exporter.git
slurm_exporter_ver: 3264648b54ba9e2c626da1277482517ff1202982
slurm_exporter_dir: /opt/slurm-exporter
slurm_exporter_host_group: "{{ slurm_monitoring_group | default('slurm-metric') }}"
slurm_exporter_svc_name: "slurm-exporter.service"
slurm_exporter_state: started
slurm_exporter_enabled: true
slurm_exporter_bin: "{{ slurm_exporter_dir }}/build/slurm_exporter"

prometheus_config_dir: /etc/prometheus
prometheus_cfg_endpoint_dir: "{{ prometheus_config_dir }}/endpoints"
slurm_exporter_conf_template: "slurm-exporter.yml.j2"

grafana_svc_name: "docker.grafana.service"
grafana_data_dir: /var/lib/grafana
grafana_cfg_dashboard_path: "{{ grafana_data_dir }}/dashboards"
grafana_user_id: 472
