---
- name: create pyxis source dir
  file:
    path: /usr/local/src/pyxis
    state: directory
    mode: "0755"
  tags: pyxis

- name: copy pyxis source
  unarchive:
    src: "{{ slurm_pyxis_tarball_url }}"
    remote_src: yes
    dest: /usr/local/src/pyxis
    extra_opts:
      - --strip-components=1
  tags: pyxis

- name: check whether spank_pyxis.so already exists
  stat:
    path: "{{ pyxis_spank_so }}"
  register: spank_pyxis_so_stat

- name: clean pyxis source directory
  command:
    chdir: /usr/local/src/pyxis
    argv:
      - make
      - clean
  register: pyxis_make_clean
  failed_when: false
  changed_when: pyxis_make_clean.rc == 0
  tags: pyxis
  when: not spank_pyxis_so_stat.stat.exists or slurm_force_install_pyxis

- name: build pyxis
  command:
    chdir: /usr/local/src/pyxis
    argv:
      - make
      - -j
  environment:
    CPPFLAGS: "-I {{ slurm_install_prefix }}/include/slurm"
  register: result
  changed_when: "result.stdout != \"make: Nothing to be done for 'all'.\""
  notify:
    - restart slurmctld
    - restart slurmd
  tags: pyxis
  when: not spank_pyxis_so_stat.stat.exists or slurm_force_install_pyxis

# Needed for 17.11, but not for 19.05. Doesn't hurt either way.
- name: copy top-level plugstack file
  template:
    src: etc/slurm/plugstack.conf
    dest: "{{ slurm_config_dir }}/"
    mode: "0644"
  notify:
    - restart slurmctld
    - restart slurmd
  tags: pyxis

- name: copy pyxis plugstack file
  template:
    src: etc/slurm/plugstack.conf.d/pyxis.conf
    dest: "{{ slurm_config_dir }}/plugstack.conf.d/"
    mode: "0644"
  notify:
    - restart slurmctld
    - restart slurmd
  tags: pyxis

- name: set pyxis shared-object permissions
  file:
    path: "{{ pyxis_spank_so }}"
    mode: 0755
