---
- name: create config dir
  file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    mode: "0755"

- name: create endpoints config dir
  file:
    path: "{{ prometheus_cfg_endpoint_dir }}"
    state: directory
    mode: "0755"

- name: install config file
  template:
    src: "{{ slurm_exporter_conf_template }}"
    dest: "{{ prometheus_cfg_endpoint_dir }}/slurm-exporter.yml"
    owner: root
    group: root
    mode: 0644

- name: create data dir
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    owner: "{{ grafana_user_id }}"
    mode: "0755"

- name: Set golang_version
  set_fact:
    golang_version: "{{ golang_version }}"

- name: Install Go lang
  include_role:
    name: gantsign.golang

- name: Clone slurm-exporter to /opt
  git:
    repo: "{{ slurm_exporter_repo }}"
    dest: "{{ slurm_exporter_dir }}"
    recursive: false
    depth: 1
    version: "{{ slurm_exporter_ver }}"

- name: Build slurm-exporter
  command:
    cmd: "{{ golang_install_dir }}/bin/go build -o {{ slurm_exporter_bin }}"
    chdir: "{{ slurm_exporter_dir }}"
    creates: "{{ slurm_exporter_bin }}"

- name: install systemd unit file
  template:
    src: templates/slurm-exporter.service.j2
    dest: "/etc/systemd/system/{{ slurm_exporter_svc_name }}"
    owner: root
    group: root
    mode: 0644
  notify: restart slurm-exporter

- name: configure service
  systemd:
    name: "{{ slurm_exporter_svc_name }}"
    state: "{{ slurm_exporter_state }}"
    enabled: "{{ slurm_exporter_enabled }}"
    daemon_reload: yes
  notify: restart slurm-exporter
